### ISSUE TITLE
Access Violation Error

### ISSUE THREAD

**Issue by Sunaries** [Elem8100/MapleStory-GM-Client#1]
Greetings,

I've downloaded the binary release of version 3.0. Upon opening the executable and choosing the MapleStory folder I get prompted with an access violation error. See image below:

![error](https://cdn.discordapp.com/attachments/236180502200057856/635607562263199754/error.png)

Every single map does not render and it gives me the same error. I also get the **Duplicates not allowed** error when opening other maps. No idea what this error means.
The program does not work on the latest version for KMS, KMST and GMS since I haven't found a workaround for the error.

**Comment by Elem8100** [comment]
Fixed,download v3.1 version

**Comment by Sunaries** [comment]
> Fixed,download v3.1 version

Thank you.

I'd like to point out that using the 'Familiar' button prompts an error (dump) . I also got a memory leak error by playing with the resolution settings. ↓

![error](https://cdn.discordapp.com/attachments/236180502200057856/645740083084787712/65565656.png)

As well as another dump error by switching maps. ↓

![error](https://cdn.discordapp.com/attachments/236180502200057856/645744261295505438/66656676.png)

Another access violation error includes summoning Mobs. 
Example) mobID 9600024 (using SEA ver.)

Is there any way to reach out to you privately? Do you have Discord? My user ID is Spadow#9286.

**Comment by Elem8100** [comment]
Fixed, download v3.11

**Comment by Sunaries** [comment]
> Fixed, download v3.11

![error](https://cdn.discordapp.com/attachments/236180502200057856/646049142736551969/4545454.png)

I used the new version and I got instantly an error when clicking the Familiar tab.

**Comment by Elem8100** [comment]
KMS and SEA "has no" Familiar, see Character.wz
