### ISSUE TITLE
如何删除头部，以用来存储发型，武器部件。

### ISSUE THREAD

**Issue by wmcxks** [Elem8100/MapleStory-GM-Client#13]
![20200701233228](https://user-images.githubusercontent.com/25580234/86263007-2c209000-bbf3-11ea-8ccf-823558d1341d.png)
希望出删除头部+躯干的按键

**Comment by wmcxks** [comment]
Avatar里如何保存没有头部躯干的PNG

**Comment by Elem8100** [comment]
你這功能要求很奇怪, 一般人應該不會這麼做, 我這編程代碼修改有點麻煩, 考慮之下決定不加了
你就用HaRepacker將Character.wz里的头部躯干圖象改成透明的就可以了

**Comment by wmcxks** [comment]
> 你这功能要求很奇怪，一般人应该不会这么做，我这编程代码修改有点麻烦，考虑之下决定不加了
> 你就用HaRepacker将Character.wz里的主轴干图像改成透明的就可以可以了
因为您的软件导出十分的方便。我想要完整动作序列帧，可是有些动作会被头部挡住。希望下个版本可以出个透明头部的部件。十分感谢 十分感谢
