### ISSUE TITLE
Hello. Could you add in a new function?

### ISSUE THREAD

**Issue by wnsgh3015** [Elem8100/MapleStory-GM-Client#18]
Hello, I like collecting map images or moving gifs. This program can be useful for that. But the chat balloons of the npc are annoying. Could you please add a function that can make the chat bubble of npc invisible? 
If you don't have a screenshot function, could you add it in?
I'd really appreciate it if you could listen to my suggestion.

**Comment by Elem8100** [comment]
> 
> 
>   Could you please add a function that can make the chat bubble of npc invisible?>
>
Download v3.41
> If you don't have a screenshot function, could you add it in?>
>
You have never tried "Save Map" Tab ?
