### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Sunaries** [Elem8100/MapleStory-GM-Client#2]
Hiya,

I would've done this myself if I had the tools for this programming language, but unfortunately I don't. Here is my feedback for your program:

**Version**: v3.11

- Change font of the application to Arial. Global (not sure of SEA) uses Arial (GDI font rendering)
 Or allow the user to change the font of the application with presets, if possible.
- Every time I launch the application, the name 'SuperGM' is visible. How can I save my own custom player name?
- 'Play Mode' does not allow me to see the entire map with my character while 'Viewer Mode' does. Why?
- _Mob/NPC Search_: Entering a name isn't smooth. You have to type letter by letter since it stops at each letter.
- _Mob/NPC Search_: Cannot use arrow keys from keyboard to go up or down the list. This also applies to other windows with a list.
- _Mob/NPC:_ How do you remove a summoned Mob/NPC?
- _NPC_: The dialogue in the speech bubble of NPCs is fast. Can you make it a little bit slower?
- Is there an option to mute map BGM?
- Can you add the option to move around the map by using arrow keys?
- Clicking the 'World Map' button prompts a window, but it doesn't show a world map.
- Assigning a skill makes my character invisible. To undo this, I need to change Mode.
- Using Full Screen mode and going back to windowed mode places the window of the program on top of all other applications.
- The path for choosing the destination folder of a MapleStory version is always linked back to the path of the application. Change it to My Computer, so people can navigate quicker through their C or D or any other partition where they usually have MapleStory installed?

**Localization improvements:**

- _Skill_: HotKeys Settigs -> Hotkey Settings
- _Skill_: HotKey -> Hotkey
- Drop Mob -> Monster (or Mob)
- Drop Npc -> NPC
- Cash -> Cash Effect
- NickName -> Title
- Label Ring -> Ring
- Delete -> Remove 
- Current Use: -> Using:
- Equip -> Avatar

**Comment by Elem8100** [comment]
v3.12
Added and fixed some of them

**Comment by Sunaries** [comment]
v3.13
Doesn't work with the latest KMST update. I get the following error upon selecting the MapleStory folder:
![error](https://cdn.discordapp.com/attachments/236180502200057856/654781159946977290/65556.png)

**Comment by Sunaries** [comment]
Feedback on **v3.2**:

**1. Search box in Avatar tab does not function properly.**
![error1](https://cdn.discordapp.com/attachments/236180502200057856/670049554846187539/error1.png)

I entered "Fluffy" and a list of items containing the word "Fluffy" appeared.

![error2](https://cdn.discordapp.com/attachments/236180502200057856/670049555265355776/error2.png)

However, there is no result when searching for the exact word match "Fluffy Bunny". It doesn't appear.

**2. Flatten hairstyles should be an optional feature to be added in since newer cash hats makes your hairstyle flat.**

![error3](https://cdn.discordapp.com/attachments/236180502200057856/670049555915472897/error3.png)

↑ This is what it looks like in the program. But it should look like this, notice the hairstyle:

![fluffy](https://cdn.discordapp.com/attachments/236180502200057856/670049565587800067/fluffybunny.png)

**3. Error upon selecting 'Dye' in the Mount window. (However, the 'Dye' tab appears in many windows.** 

![error4](https://cdn.discordapp.com/attachments/236180502200057856/670050961594515476/error4.png)

**4. Foreign text in Mob window and the color of the box is not white.** 

![error5](https://cdn.discordapp.com/attachments/236180502200057856/670051607420993547/error5.png)

**5. The 'Save Map' feature does not work properly. If saved, it only saves a portion of the image and not the entire map with your character and map data in it.**

![elliniamap](https://cdn.discordapp.com/attachments/236180502200057856/670053516823232543/180000100-Ellinia.png)

**6. Changing window resolution prompts access violation errors.**

![error6](https://cdn.discordapp.com/attachments/236180502200057856/670053738907697173/error6.png)

**7. The position for viewing the map in Play Mode is off. It should be like in Viewer Mode, that you can control your character in Play Mode and see your character properly.**

![error7](https://cdn.discordapp.com/attachments/236180502200057856/670056767753027584/error7.png)

↑ The position is weird because now it looks like a portion has been cut off.

**8. Arial font.**
Can you please add 'Arial' (12f for in-game text such as NPC names, item names etc.) to the program. Or at least make it an optional setting through Settings. 

Thanks for fixing some of the feedback that was given earlier. Great job on the program. 👍

**Comment by Sunaries** [comment]
**Bug with Cash Effects.**
![error1](https://cdn.discordapp.com/attachments/236180502200057856/672633612524584990/45.png)

Not properly positioned.

**Comment by Sunaries** [comment]
**Bug with chair**
![error1](https://cdn.discordapp.com/attachments/236180502200057856/702609825158135978/chair1.png)

You can see the legs ('sit' position) of the character which should not appear. The item ID is 03018349. It should be like this:

![error2](https://cdn.discordapp.com/attachments/248315264104529920/702566266056999002/newtro_1b_dance_chair.gif)

I think I've mentioned this in an earlier post, but searching is not working fine.

![roller1](https://cdn.discordapp.com/attachments/236180502200057856/702609610715955220/roller1.png)

Entering the keyword "roller" shows all items related to the keyword, but fully entering the item name will not show the item on the menu.

![roller2](https://cdn.discordapp.com/attachments/236180502200057856/702609611408146542/roller2.png)
