### ISSUE TITLE
怎么把上衣的mailChest和mailArm这两个部件分别导出成两个独立的.png图片文件

### ISSUE THREAD

**Issue by BuladeMian** [Elem8100/MapleStory-GM-Client#20]
如题

**Comment by BuladeMian** [comment]
![21](https://user-images.githubusercontent.com/24313172/91636529-f56cc780-ea33-11ea-99cc-e7a83bd45a35.png)
![22](https://user-images.githubusercontent.com/24313172/91636532-f6055e00-ea33-11ea-8314-6e42c92eca12.png)

**Comment by Elem8100** [comment]
同時一起render的, 無法分開
