### ISSUE TITLE
TMS古代之弓系列武器都無法加載

### ISSUE THREAD

**Issue by rixer9090** [Elem8100/MapleStory-GM-Client#24]
如題，使用的是最新版的TMS V235.2
人物換裝使用古代之弓的時候都會出現Access violation at address......
希望能有解決方法，我想用出我的角色，職業剛好是開拓者QAQ

**Comment by Elem8100** [comment]
已修復
https://www.mediafire.com/file/8uep36yjf298uxa/MapleStoryEmulator_V3.5.1.rar/file
