### ISSUE TITLE
BUG回報

### ISSUE THREAD

**Issue by HolyBearTW** [Elem8100/MapleStory-GM-Client#25]
1.特效類披風顯示的位置偏掉，另外凱殷的龍息射手也無法正常顯示
Ex:[連結](https://truth.bahamut.com.tw/s01/202105/58d10631d92d8d30274bca1e31a6dcf2.JPG)
2.韓版最新1.2.351版本部份地圖無法正常載入，會跳錯誤，有些地圖可以載入但不會顯示BGM
Ex:[連結](https://truth.bahamut.com.tw/s01/202107/bcd1dc97ade480a0832773843cfd8317.JPG)
3.特定道具只要套用上去的話，程式會直接崩潰(EX.破滅的鞋子/真破滅的鞋子、生命的鞋子/真生命的鞋子)
4.在TMS最新版上打開物品欄有許多地方有嚴重位移的情形

**Comment by Elem8100** [comment]
4.暫時不修
1、2、3項已修復(v3.6)
https://www.mediafire.com/file/5vq7chd8ogwe60b/MapleStoryEmulator_V3.6.rar/file

**Comment by Elem8100** [comment]
v3.6大致測試沒問題，v3.5、v3.51的中文版載點已刪除，只有Github提供英文版的舊版

**Comment by HolyBearTW** [comment]
好的，辛苦大大了!

**Comment by HolyBearTW** [comment]
@Elem8100 您好，回報幾個新問題，經網友反饋：
1. 這次換成特效類型披風在人物朝右以及爬繩子梯子狀態時位置會右偏很多
https://truth.bahamut.com.tw/s01/202109/db947dd8f4c19454074cc33e843aee86.JPG
2. 神燈妖精溫莉(點武)會跳錯誤的問題

**Comment by Elem8100** [comment]
第1項v3.7已修復了

P.S.
v3.6載點已刪除

**Comment by HolyBearTW** [comment]
@Elem8100 您好，在最新韓版正服ver1.2.357有無法使用問題，再請麻煩確認。

**Comment by Elem8100** [comment]
好的,近期會修復

**Comment by Elem8100** [comment]
已修復
https://github.com/Elem8100/MapleStory-GM-Client/releases

**Comment by HolyBearTW** [comment]
@Elem8100 網友反應3.8版的儲存角色功能無法正常使用，再麻煩了，謝謝！

**Comment by Elem8100** [comment]
3.8與3.81測試都正常
他該不會是在rar裡直接執行? 還是角色儲存太多隻沒看到

**Comment by HolyBearTW** [comment]
@Elem8100 測試後問題排除，應該是他的問題，感謝協助測試。

**Comment by a406010503** [comment]
@Elem8100 回報韓版v1.2.360無法使用 [圖片連結](https://truth.bahamut.com.tw/s01/202202/b34cb8e2d5c7e1b31196b7ef59ab0f26.PNG)

**Comment by HolyBearTW** [comment]
@Elem8100 網友反應MSEA v212版本 無法開啟，[圖片1](https://i.imgur.com/sF5IOCI.png)、[圖片2](https://i.imgur.com/TNQjUlh.png)

**Comment by HolyBearTW** [comment]
@Elem8100 網友回報JMS最新版本無法開啟，[圖片](https://truth.bahamut.com.tw/s01/202203/bb52459cd7d4cc60f8387a04a78a174b.PNG)
