### ISSUE TITLE
Is it possible to add new function?

### ISSUE THREAD

**Issue by yongsing17** [Elem8100/MapleStory-GM-Client#26]
Hello, I wonder whether adding the function of viewing the images such as character illustration and the pictures in storylines is possible. I just want to see the ordinary pictures files....if that is a big work, you don't have to do it. Thanks for building this useful app.

**Comment by Elem8100** [comment]
This is not WZ file viewer.You can try WZCompareR2
https://github.com/Kagamia/WzComparerR2
or HaRepacker
https://github.com/lastbattle/Harepacker-resurrected
