### ISSUE TITLE
一打开wz文件就报错怎么解决啊

### ISSUE THREAD

**Issue by HomoGia** [Elem8100/MapleStory-GM-Client#27]

**Comment by HomoGia** [comment]
是一定要最新版本客户端才可以吗？![IMG_20211018_111646.jpg](https://user-images.githubusercontent.com/91911997/137663999-34d1fd5b-07ab-4465-b9b3-4741174119a1.jpg)

**Comment by Elem8100** [comment]
哪個版本?

**Comment by HomoGia** [comment]
079的版本

**Comment by Elem8100** [comment]
079沒問題啊
你左上角的選項有切換EMS/KMS(old) 嗎 ?
![Image 10](https://user-images.githubusercontent.com/49195287/137909233-477523c9-cbea-4488-975f-5f8687c13605.jpg)

**Comment by HomoGia** [comment]
有切换啊，但是还是报错

**Comment by HomoGia** [comment]
我是下载的最新版的

**Comment by Elem8100** [comment]
你的冒險島路徑選擇錯誤 ,是要選里面有xxx.wz的文件夾, 不是最上層的文件夾
例如:
C:/079/冒險島Online 
要選 冒險島Online, 而不是079

**Comment by HomoGia** [comment]
😂这个我倒是没注意，但是应该没有选错才对

**Comment by Elem8100** [comment]
現在可以了吧, 還會出錯嗎?

**Comment by HomoGia** [comment]
我还没来得及试验，还在外面，没到家

**Comment by HomoGia** [comment]
还是不行呢。选中了私服端文件夹还是报错

**Comment by Elem8100** [comment]
私服的wz有改過造成無法讀取, 這問題沒辦法解決的
你只能用官方純淨版的079

**Comment by HomoGia** [comment]
啊。那官方纯净的079上哪下载啊

**Comment by Elem8100** [comment]
沒079,建議075以後的
https://msdl.xyz/pages/cms/setups

**Comment by HomoGia** [comment]
厉害了，方便加您一个微信吗

**Comment by HomoGia** [comment]
😰不方便吗

**Comment by Elem8100** [comment]
我沒在用微信的

**Comment by HomoGia** [comment]
line？
