### ISSUE TITLE
Is it possible to add debugger mode to track coordinates of mobs, npcs, characters, etc?

### ISSUE THREAD

**Issue by nanpuhaha** [Elem8100/MapleStory-GM-Client#28]
Is it possible to add debugger mode to track coordinates of mobs, npcs, characters, etc?
I want to make vision based learning machine using python which can be detect characters, effects, items, maps, mobs, npcs, skills, taming mobs, ui elements.

**Comment by Elem8100** [comment]
This tool's main goal is MapleStory client simulation. I have no plan to do that.

**Comment by nanpuhaha** [comment]
Okay. Thank you for the great project.
