### ISSUE TITLE
無法用於gms部分版本

### ISSUE THREAD

**Issue by Kongwan333** [Elem8100/MapleStory-GM-Client#30]
你好，我在使用GMS V176 以及 GMS V183測試過程中遇到了錯誤，
GM Client可以正確地讀取到信息，但在點選載入地圖時會產生錯誤：
wz文件是乾淨的原版客戶端文件，我很確定他們沒有被修改過。
相關的錯誤截圖如下：
![image](https://user-images.githubusercontent.com/48130365/146646916-31db7e2a-acb5-4d45-aa34-3f6f1dbf2e8f.png)
![image](https://user-images.githubusercontent.com/48130365/146646931-bb66a553-4f9a-40ae-a1af-d0181fd48189.png)

**Comment by Elem8100** [comment]
已修復
