### ISSUE TITLE
Now the latest version doesn't work saying : Unknown Marker at ParseDirectory(Base) : i = 0; Marker 0.

### ISSUE THREAD

**Issue by DokyeongLee-3** [Elem8100/MapleStory-GM-Client#31]
Now the latest version doesn't work saying : Unknown Marker at ParseDirectory(Base) : i = 0; Marker 0.
I think the reason is the latest patch from the game. Is there any plan to Update the GMClient?

Best regards

**Comment by Elem8100** [comment]
Fixed. Work fine with v360.

**Comment by DokyeongLee-3** [comment]
Thank you for your fast fix and release.

I will fix this issue right now. Thank you again 👍
