### ISSUE TITLE
[V3.9] Unable to load GMS v230

### ISSUE THREAD

**Issue by Sunaries** [Elem8100/MapleStory-GM-Client#32]
Hi,

I have downloaded the most recent version v3.9, but upon selecting the GMS directory I am prompted with an error. Other versions work.
See image:

![](https://i.imgur.com/F5gRAyi.png)

GMS v229 works.

![error](https://i.imgur.com/gdADLfh.png)

GMS v230 doesn't work.

**Comment by Elem8100** [comment]
I haven't installed v230. Please try v3.81 and tell me the result.

**Comment by Sunaries** [comment]
> I haven't installed v230. Please try v3.81 and tell me the result.

Does not work. It probably doesn't work because of [this change](https://github.com/Kagamia/WzComparerR2/issues/194).

**Comment by Elem8100** [comment]
Try this. Select GMS(new)
https://www.mediafire.com/file/4va56x9su9jhmjg/MapleStoryGM_v3.91.rar/file
![Image 3](https://user-images.githubusercontent.com/49195287/153765393-b4034d2d-7942-470c-a2c3-c1d6eda7fd22.jpg)

**Comment by Sunaries** [comment]
> Try this. Select GMS(new) https://www.mediafire.com/file/4va56x9su9jhmjg/MapleStoryGM_v3.91.rar/file ![Image 3](https://user-images.githubusercontent.com/49195287/153765393-b4034d2d-7942-470c-a2c3-c1d6eda7fd22.jpg)

Works!
