### ISSUE TITLE
無法開啟回報

### ISSUE THREAD

**Issue by HolyBearTW** [Elem8100/MapleStory-GM-Client#33]
1. 網友反應MSEA v212版本 無法開啟，[圖片1](https://i.imgur.com/sF5IOCI.png)、[圖片2](https://i.imgur.com/TNQjUlh.png)
2. 網友反應JMS最新版本無法開啟，[圖片](https://truth.bahamut.com.tw/s01/202203/bb52459cd7d4cc60f8387a04a78a174b.PNG)

**Comment by Elem8100** [comment]
選擇國際版(新) 就可以了，MSEA和JMS都一樣
![Image 1](https://user-images.githubusercontent.com/49195287/160282782-932b5314-3249-4f94-809b-0db9991d0887.jpg)

**Comment by HolyBearTW** [comment]
好的，這個細節確實沒有注意到，已轉達。

**Comment by a406010503** [comment]
@Elem8100 
網友反應 TMS v257版本更新後載入會提示英文字母【Item not found.】的警告
再麻煩查看，謝謝~
