### ISSUE TITLE
3019XXX编号的椅子 无法预览

### ISSUE THREAD

**Issue by dskytian** [Elem8100/MapleStory-GM-Client#36]
![QQ图片20230116210830](https://user-images.githubusercontent.com/122798036/212686335-f0afb0bb-562f-4a75-abe7-518424d89e0e.png)

**Comment by Elem8100** [comment]
好的,我看看

**Comment by Elem8100** [comment]
已修復

**Comment by dskytian** [comment]
> 已修复

OK
