### ISSUE TITLE
GMS v239 Not Working

### ISSUE THREAD

**Issue by DorWeid** [Elem8100/MapleStory-GM-Client#38]
Getting this error when trying to open GMS folder:
![image](https://user-images.githubusercontent.com/13677126/219720371-b8f714e5-d0a5-41a2-a805-3dd9f494616a.png)

**Comment by Elem8100** [comment]
Try change to first item(KMS/SEA/BMS)

**Comment by DorWeid** [comment]
Similar result, this time on `Etc` directory (to be clear, I tried it with all options):
![image](https://user-images.githubusercontent.com/13677126/219844766-1221aa00-96c7-49c7-9a3e-38eb8221940a.png)

**Comment by Elem8100** [comment]
GMS v239 worked fine for me. Did you use modified version of wz file?
You must use clean official wz files  
![Image 1](https://user-images.githubusercontent.com/49195287/219855540-948e7a1a-3e0b-4e3e-8e65-f4957c53830a.jpg)

**Comment by DorWeid** [comment]
You're right. Looks like I had a modified folder. Thanks
