### ISSUE TITLE
Can't open the mapleStoryGM.exe

### ISSUE THREAD

**Issue by gphoneyo** [Elem8100/MapleStory-GM-Client#39]
I get a error window, when I open the mapleStoryGM.exe.

The error message is Runtime error in 217 at 40C96558

**Comment by gphoneyo** [comment]
Did I do something wrong ?

**Comment by Elem8100** [comment]
It's working fine with Win10/11.It may caused by some sort of hardware.But i really can't help.

**Comment by gphoneyo** [comment]
> 

Thanks for reply. I changed another computer and the software runs well. Maybe there's something wrong with my old computer lol. Anyways, thank you.
