### ISSUE TITLE
Hellow 又是我，關於 KMST 的 _Canvas 一事

### ISSUE THREAD

**Issue by FCL2025** [Elem8100/MapleStory-GM-Client#40]
請問MapleStoryEmulator 
有辦法處理上次提到的韓測檔案問題嗎?

再修椅子但是沒辦法查看正服坐椅子的狀態。

**Comment by Elem8100** [comment]
已經移植到C#版了

https://github.com/Elem8100/MapleNecrocer

**Comment by FCL2025** [comment]
OK thank you
