### ISSUE TITLE
能否考虑做一个做一个读取接口的img信息版本的呢

### ISSUE THREAD

**Issue by ahao0150** [Elem8100/MapleStory-GM-Client#43]
比如这个是在线获取各个版本的冒险岛的wz文件信息
https://browse-old.maplestory.io/#GMS;83;Skill/000.img/skill/0001011/affected/0

然后这个是新版的获取接口网站
https://maplestory.io/

是不是可以做成不用下载客户端就能加载各个版本的冒险岛。

**Comment by Elem8100** [comment]
目前支持最完善、功能最強的WzLib就是WzComparerR2，你要自己轉換成其他編程語言
我這是單機模擬器 不是web，無法幫你

**Comment by ahao0150** [comment]
好的，谢谢。
