### ISSUE TITLE
客户端拆分后 已无法读取

### ISSUE THREAD

**Issue by dskytian** [Elem8100/MapleStory-GM-Client#45]
韩版在6转改版的时候每个WZ拆分了_Canvas
目前JMS MSEA GMS都已更新
TMS CMS将在11月底更新
所以希望针对此次修改进行更新
![%7B82D95121-CD90-4727-B848-317CF89F40B7%7D](https://github.com/Elem8100/MapleStory-GM-Client/assets/122798036/f82262b9-e4d3-4afa-8a04-f66a5c12acad)

**Comment by Elem8100** [comment]
https://github.com/Elem8100/MapleStory-GM-Client/issues/44
https://github.com/Elem8100/MapleStory-GM-Client/issues/41
https://github.com/Elem8100/MapleStory-GM-Client/issues/40

**Comment by dskytian** [comment]
好的感谢
