### ISSUE TITLE
GMS客户端更新后无法使用

### ISSUE THREAD

**Issue by RyougiMirai** [Elem8100/MapleStory-GM-Client#46]
之前可用，最近更新后 首次读取地图报错如下图：
![20231115232652](https://github.com/Elem8100/MapleStory-GM-Client/assets/23241693/ccc29c77-ce4b-49c0-95c5-34aeb5651f64)
再次尝试读取地图 报错如下图：
![20231115232742](https://github.com/Elem8100/MapleStory-GM-Client/assets/23241693/ba8f53cd-2b4d-4084-835d-e207b0ddc906)
试过2台电脑，都一样问题无法正常运行
这个工具是最好用的MapleFashion模拟器 没有之一，比WEB端的maples.im强大太多，请作者大大修复这个BUG

**Comment by Elem8100** [comment]
這問題已經被問N次了
https://github.com/Elem8100/MapleStory-GM-Client/issues/45
https://github.com/Elem8100/MapleStory-GM-Client/issues/44
https://github.com/Elem8100/MapleStory-GM-Client/issues/41
https://github.com/Elem8100/MapleStory-GM-Client/issues/40

**Comment by RyougiMirai** [comment]
好的谢谢，已经看到说明
