### ISSUE TITLE
TMS113自由市場加載失敗

### ISSUE THREAD

**Issue by fmnijk** [Elem8100/MapleStory-GM-Client#5]
![12345](https://user-images.githubusercontent.com/52465927/73780369-52b7d780-47c9-11ea-935a-47059313eed1.png)

**Comment by Elem8100** [comment]
我沒v113但是v122沒問題,你地圖應該修改過

**Comment by fmnijk** [comment]
我用的是官方的安裝檔，應該是沒改過的
https://mega.nz/#!IbISFaKT!ahFyvOdbAp9kW5Ye3u9jlBPA8xksvTh9w7EbsHyxDT0

**Comment by Elem8100** [comment]
Npc 9330122不在string.wz裡面造成讀取錯誤，下次更新會修正
