### ISSUE TITLE
编译不了

### ISSUE THREAD

**Issue by fuhx** [Elem8100/MapleStory-GM-Client#6]
兄弟，看你更新还挺勤的，可为何每次下载下来都是编译不了的呢？
除了 Release 里的  v3.13 可编译外，其他版本都是编译不了的，包括从 master 下载的也是。

**Comment by Elem8100** [comment]
目前開發測試是用中文版的, github裡的只是.pas單元更正

**Comment by fuhx** [comment]
谢谢，afterwarp.dll 似乎中毒了，到官网重新下载了一个，不会报毒了 https://afterwarp.io/downloads

**Comment by y2kwill2000** [comment]
奇怪樓上的說v3.13能編譯成功但我沒半個可以編譯成功
