### ISSUE TITLE
Errors compiler

### ISSUE THREAD

**Issue by Sesillabubu** [Elem8100/MapleStory-GM-Client#7]
Hi,

How can i compile source? I have many errors with:
TMapPortal.Create(SpriteEngine) --> E2250 There is no overloaded version of 'Create' that can be called with these arguments

TObjectDictionary<TWZIMGEntry, TDX9LockableTexture> vs TObjectDictionary<TWZIMGEntry, TTexture>

and others?

Thanks in advance
Sesilla

**Comment by Elem8100** [comment]
You must have Delphi 10.3 or later.
Install Third-Party component:
1.TMS Component Pack
2.ImageEn
3.AlmediaDev StyleControl

Add common library path:
Tools->Options->Language->Delphi Options->Library

My Library path sample:
D:\imageen\delphi10.3rio
D:\Almediadev StyleControls 4.25 Full Source Retail
D:\TMS Component Pack9020
D:\MapleStoryAfterwarp\WZlib
D:\MapleStoryAfterwarp\DEC
D:\MapleStoryAfterwarp\zlib
D:\MapleStoryAfterwarp\AsphyreSphinx\Source
D:\MapleStoryAfterwarp\Bass
D:\MapleStoryAfterwarp\ZSource
D:\MapleStoryAfterwarp\Afterwarp\source

the current Englist version can't compile. It is not  finished yet.
then Download this(Chinese versin):
http://www.mediafire.com/file/sps48amojkoi2ym/MapleStoryAfterwarp.rar/file
